import { Image } from "react-grid-gallery";

export const images = [
  {
    src: "https://i.ibb.co/J5RCVnf/DSC-7609.jpg",
    original: "https://i.ibb.co/J5RCVnf/DSC-7609.jpg",
    alt: "Big Ben - London",
    width: 320,
    height: 213,
    caption: "Big Ben (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/GWKchzs/DSC-7621.jpg",
    original: "https://i.ibb.co/GWKchzs/DSC-7621.jpg",
    alt: "Red Zone - Paris",
    width: 320,
    height: 213,
    tags: [{ value: "Cabina vintage", title: "Cabina 360" }],
    caption: "Red Zone - Paris (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/gM8bHgN/DSC-7726.jpg",
    original: "https://i.ibb.co/gM8bHgN/DSC-7726.jpg",
    alt: "Wood Glass",
    width: 320,
    height: 213,
    caption: "Wood Glass (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/xX8gMmG/DSC-7798.jpg",
    original: "https://i.ibb.co/xX8gMmG/DSC-7798.jpg",
    width: 320,
    height: 213,
    caption: "Flower Interior Macro (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/wW6326Y/DSC-9619.jpg",
    original: "https://i.ibb.co/wW6326Y/DSC-9619.jpg",
    width: 200,
    height: 213,
    caption: "Old Barn (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/kGR7NZQ/DSC-8772.jpg",
    original: "https://i.ibb.co/kGR7NZQ/DSC-8772.jpg",
    alt: "Cosmos Flower",
    width: 320,
    height: 213,
    caption: "Cosmos Flower Macro (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/tMHdDDp/DSC-8825.jpg",
    original: "https://i.ibb.co/tMHdDDp/DSC-8825.jpg",
    width: 320,
    height: 213,
    caption: "Orange Macro (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/pQtHfPP/DSC-8941.jpg",
    original: "https://i.ibb.co/pQtHfPP/DSC-8941.jpg",
    width: 320,
    height: 213,
    tags: [{ value: "Cabina 360", title: "Cabina 360" }],
    caption: "Surfer Sunset (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/Zhws3kc/DSC-9848.jpg",
    original: "https://i.ibb.co/Zhws3kc/DSC-9848.jpg",
    width: 320,
    height: 213,
    tags: [
      { value: "Evento Navidad", title: "People" },
    ],
    caption: "Man on BMX (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/2PnVxm7/DSC-7741.jpg",
    original: "https://i.ibb.co/2PnVxm7/DSC-7741.jpg",
    width: 320,
    height: 213,
    caption: "Ropeman - Thailand (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/10QgWD2/IMG-4964.jpg",
    original: "https://i.ibb.co/10QgWD2/IMG-4964.jpg",
    width: 220,
    height: 213,
    caption: "Time to Think (Tom Eversley - isorepublic.com)",
  },
  {
    src: "https://i.ibb.co/VjG8ktZ/DSC-7743.jpg",
    original: "https://i.ibb.co/VjG8ktZ/DSC-7743.jpg",
    width: 380,
    height: 213,
    tags: [
      { value: "Cabina Vintage", title: "Nature" },
    ],
    caption: "Untitled (Jan Vasek - jeshoots.com)",
  }
];
